---
abstract: 'show all Perl packages provided or required'
author:
  - 'Andrew Pam <andrew.pam@strategicdata.com.au>'
build_requires:
  Test::Differences: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: pmcheck
provides:
  App::pmcheck:
    file: lib/App/pmcheck.pm
    version: v1.1.11
recommends:
  Module::Used: 0
  Term::Activity: 0
requires:
  PPI::Document: 0
  perl: v5.10.0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v1.1.11
